name: ci
on:
  push:
    branches: [main, v2]
  pull_request:
    branches: ['*']

jobs:
  deno:
    name: 'Deno'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run:  deno install
      - run:  deno run --sloppy-imports -A npm:vitest run

  bun:
    name: 'Bun'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.10'
      - run: bun install
      - run: bun test

  node:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20.x', '22.x', '24.x']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --frozen-lockfile
      - run: npm run test
